module.exports = function(grunt) {

	grunt.initConfig({
		srcFolder: 'src',
		baseFolder: 'dest',
		pkg: grunt.file.readJSON('package.json')
	});

	/* compass */
	grunt.loadNpmTasks('grunt-contrib-compass');
	grunt.config('compass', {
		dev : {
			options: {
				sassDir: '<%= srcFolder %>/scss',
				cssDir: '<%= baseFolder %>/css',
				outputStyle : 'nested',
				environment: 'development'
			}
		}
	});

	/* watch */
	grunt.loadNpmTasks('grunt-contrib-watch');
	grunt.config('watch', {
		options: {
			livereload: '<%= connect.options.livereload %>',
		},
		all : {
			files: ['<%= srcFolder %>/**/*', 'Gruntfile.js', 'node_modules/grunt-shower-markdown/**/*'],
			tasks: ['shower','compass']
		}
	});

	/* connect */
	grunt.loadNpmTasks('grunt-contrib-connect');
	grunt.config('connect', {
		options: {
			port: 8080,
			livereload: 35729,
			hostname: 'localhost'
		},
		livereload: {
			options: {
				open: true,
				base: '<%= baseFolder %>'
			}
		}
	});

	/* deploy gh-pages  */
	grunt.loadNpmTasks('grunt-gh-pages');
	grunt.config('gh-pages', {
		options: {
			base: 'www' ,
			message: 'Generated by grunt gh-pages'
		},
		src: [
			'css/*',
			'font/*',
			'img/*',
			'shower/*',
			'themes/**/*',
			'index.html'
		]
	});

	/* tasks  */
	grunt.loadNpmTasks('grunt-available-tasks');
	grunt.config('availabletasks', {
		tasks: {
			options: {
				/* showTasks: ['user'], */
				sort: true
			}
		}
	});

	grunt.registerTask ('deploy', ['default','gh-pages']);
	grunt.registerTask('serve', ['default','connect:livereload','watch:all']);
	grunt.registerTask('tasks', ['availabletasks']);
	grunt.registerTask('default', ['compass']);

};